# Generated by Django 4.2.23 on 2025-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Craft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("craft_name", models.CharField(max_length=255)),
                ("craft_image", models.ImageField(upload_to="crafts")),
                ("material_used", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
                ("craft_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
