# Generated by Django 4.2.23 on 2025-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("director", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("rating", models.FloatField()),
                ("duration", models.TimeField()),
                ("language", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("watched", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
