# Generated by Django 4.2.23 on 2025-10-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(help_text="Duration (e.g. 2:29:00 or '2h 29m')"),
        ),
    ]
